{% set name = "distrax" %}
{% set version = "0.1.7" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-deepmind/distrax/archive/v{{ version }}.tar.gz
  sha256: 66ad1adc84c592c6a3e225103e0af902d2247a4b76b5bb3e8dbbf4b3e2904cc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - absl-py >=0.9.0
    - chex >=0.1.8
    - jax >=0.1.55
    - jaxlib >=0.1.67
    - numpy >=1.23.0
    - tensorflow-probability >=0.15.0

test:
  requires:
    - python {{ python_min }}
    - dm-haiku
    - flax
    - mock
  imports:
    - distrax
  commands:
    - JAX_DISABLE_MOST_OPTIMIZATIONS=True pytest --pyargs distrax -k 'not _float64_test'

about:
  home: https://github.com/deepmind/distrax
  summary: 'Distrax: Probability distributions in JAX.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - flferretti
