{% set name = "distrax" %}
{% set version = "0.1.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-deepmind/distrax/archive/v{{ version }}.tar.gz
  sha256: 06d7c049f12f94d6e6c1a54aa26eb95eb488af8d1dc68589d54506a2ae479993
  patches:
    - 01-exclude-examples.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - absl-py >=0.9.0
    - chex >=0.1.8
    - jax >=0.1.55
    - jaxlib >=0.1.67
    - numpy >=1.23.0
    - tensorflow-probability >=0.15.0

test:
  imports:
    - distrax

about:
  home: https://github.com/deepmind/distrax
  summary: 'Distrax: Probability distributions in JAX.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - flferretti
